const texts = {
  en: {
    login: "Login",
    authorization: "Authorization",
    register: "Register",
    registration: "Registration",
    resetPassword: "Reset Password",
    home: "Home",
    crosses: "Crosses",
    rings: "Rings",
    bracelets: "Bracelets",
    earings: "Earings",
    chains: "Chains",
    watches: "Watches",
    coins: "Coins",
    other: "Other",
    search: "Search",
    choose: "Choose",
    category: "Category",
    weight: "Weight",
    price: "Price",
    GEL: "GEL",
    products: "Products",
    email: "Email",
    password: "Password",
    notRegistered: "Not registered?",
    alreadyRegistered: "Already registered?",
    forgotPassword: "Forgot password?",
    nickname: "Nickname",
    repeatPassword: "Repeat Password",
    choosePrice: "Choose price range",
    chooseWeight: "Choose weight",
    minWeight: "min. weight",
    maxWeight: "max. weight",
    minPrice: "min. price",
    maxPrice: "max. price",
    gram: "gram",
    any: "any",
    resetPassword: "Resset password",
    newPassword: "New password",
    changePassword: "Change password",
    pleaseLogin: "Please login!",
    addItem: "Add item",
    add: "Add",
    title: "Title",
    probe: "Standard",
    description: "Description",
    dragNdrop: "Drag 'n' drop some files here, or click to select files",
    image: "Image",
    max5: "max. 5",
    max5images: "Maximum 5 images allowed",
    min1image: "Please, upload at least 1 image",
    categories: "Categories",
    profile: "Profile",
    myItems: "My items",
    requiredField: "Field is required",
    myAccount: "My account",
    logout: "Log out",
    resended:
      "Email not verified. A new verification email has been sent. Check your email for instructions!",
    resend: "Resend",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    userUpdated: "User data updated successfuly",
    confirmWithPassword: "Confirm changes with current password",
    noChanges: "No changes detected",
    incorrectPassword: "Incorect password",
    currentPassword: "Current password",
    mobileNumber: "Mobile number",
    firstName: "First Name",
    lastName: "Last Name",
    shopName: "Name of your shop",
    update: "Update",
    verify: "Verify",
    notVerified: "Email not verified",
    emailVerified: "Email verified!",
    goFilter: "Go",
    topic: "Buy / sell gold items",
    view: "View",
    contact: "contact",
    metal: "Metal",
    gold: "Gold",
    silver: "Silver",
    wishlist: "Wishlist",
    share: "share",
  },
  ka: {
    login: "შესვლა",
    authorization: "ავტორიზაცია",
    register: "რეგისტრაცია",
    registration: "რეგისტრაცია",
    resetPassword: "პაროლის აღდგენა",
    home: "მთავარი",
    crosses: "ჯვრები",
    rings: "ბეჭდები",
    bracelets: "სამაჯურები",
    earings: "საყურეები",
    chains: "ჯაჭვები",
    watches: "საათები",
    coins: "მონეტები",
    other: "სხვა",
    topic: "ოქროს ნივთების ყიდვა/გაყიდვა",
    search: "ძიება",
    choose: "აირჩიეთ",
    category: "კატეგორია",
    weight: "წონა",
    price: "ფასი",
    GEL: "ლარი",
    products: "პროდუქტები",
    email: "ელ-ფოსტა",
    password: "პაროლი",
    notRegistered: "არ გაქვს ანგარიში?",
    alreadyRegistered: "უკვე დარეგისტრირებული ხარ?",
    forgotPassword: "დაგავიწყდა პაროლი?",
    nickname: "მეტსახელი",
    repeatPassword: "გაიმეორეთ პაროლი",
    choosePrice: "აირჩიეთ ფასის დიაპაზონი",
    chooseWeight: "აირჩიეთ წონა",
    minWeight: "მინ. წონა",
    maxWeight: "მაქს. წონა",
    minPrice: "მინ. ფასი",
    maxPrice: "მაქს. ფასი",
    gram: "გრამი",
    any: "ნებისმიერი",
    resetPassword: "პაროლის აღდგენა",
    newPassword: "ახალი პაროლი",
    changePassword: "პაროლის შეცვლა",
    pleaseLogin: "გთხოვთ, გაიაროთ ავტორიზაცია!",
    addItem: "დაამატე ნივთი",
    add: "დამატება",
    title: "დასახელება",
    probe: "სინჯი",
    description: "აღწერა",
    dragNdrop: "ჩაყარეთ სურათები აქ ან დააჭირეთ ასატვირთად",
    image: "სურათი",
    max5: "მაქს. 5",
    max5images: "თქვენ შეგიძლიათ ატვირთოთ მაქსიმუმ 5 სურათი",
    min1image: "გთხოვთ, ატვირთოთ მინიმუმ 1 სურათი",
    categories: "კატეგორიები",
    profile: "პროფილი",
    myItems: "ჩემი ნივთები",
    requiredField: "აუცილებელი ველი",
    myAccount: "ჩემი ანგარიში",
    logout: "გასვლა",
    resended:
      "თქვენი ანგარიში ვერიფიცირებული არ არის. შეამოწმეთ თქვენი ელ-ფოსტა, ახალი ვერიფიკაციის კოდისათვის!",
    selectAll: "ყველა",
    deselectAll: "არცერთი",
    resend: "ხელახლა გაგზავნა",
    userUpdated: "მონაცემები წარმატებით შეიცვალა",
    confirmWithPassword: "დაადასტურეთ ცვლილებები",
    noChanges: "ცვლილებები არ არის",
    incorrectPassword: "პაროლი არასწორია",
    currentPassword: "მიმდინარე პაროლი",
    mobileNumber: "მობილურის ნომერი",
    firstName: "სახელი",
    lastName: "გვარი",
    shopName: "თქვენი შოპის სახელწოდება",
    update: "განახლება",
    verify: "ვერიფიკაცია",
    notVerified: "თქვენი ელ-ფოსტა ვერიფიცირებული არ არის",
    emailVerified: "ელ-ფოსტის ვერიფიკაცია წარმატებით დასრულდა!",
    goFilter: "ძიება",
    view: "ნახვა",
    contact: "კონტაქტი",
    metal: "ლითონი",
    gold: "ოქრო",
    silver: "ვერცხლი",
    wishlist: "მოწონებულები",
    share: "გაზიარება",
  },
};

export default texts;
